"""Inbound use cases depend only on these outbound ports and pure domain types."""

from __future__ import annotations

from typing import Protocol

from app.domain.entities import Order, Product, Session, User


class UserRepository(Protocol):
    def get(self, user_id: int, lock: bool = False) -> User | None: ...
    def by_email(self, email: str, lock: bool = False) -> User | None: ...
    def by_google(self, subject: str) -> User | None: ...
    def save(self, user: User) -> User: ...


class SessionRepository(Protocol):
    def get(self, digest: str, lock: bool = False) -> Session | None: ...
    def save(self, session: Session): ...
    def revoke(self, user_id: int, now, digest: str | None = None): ...


class ProductRepository(Protocol):
    def get(self, product_id: str) -> Product | None: ...
    def get_many(self, product_ids: list[str]) -> dict[str, Product]: ...
    def search(self, query: str | None, category: str | None, limit: int) -> list[Product]: ...


class CartRepository(Protocol):
    def list(self, user_id: int) -> list[tuple[str, int]]: ...
    def put(self, user_id: int, product_id: str, quantity: int): ...
    def clear(self, user_id: int): ...


class WishlistRepository(Protocol):
    def list(self, user_id: int) -> list[str]: ...
    def put(self, user_id: int, product_id: str): ...
    def remove(self, user_id: int, product_id: str): ...


class OrderRepository(Protocol):
    def get(self, order_id: int, user_id: int | None = None, lock: bool = False) -> Order | None: ...
    def list(self, user_id: int) -> list[Order]: ...
    def save(self, order: Order) -> Order: ...
    def due(self, now, limit: int = 100) -> list[int]: ...


class InventoryRepository(Protocol):
    def reserve(self, product_id: str, quantity: int) -> bool: ...
    def release(self, product_id: str, quantity: int): ...


class TokenRepository(Protocol):
    def issue(self, user_id, purpose, digest, expires_at, payload=None): ...
    def find(self, purpose, digest): ...
    def consume(self, purpose, digest, now): ...
    def clear(self, user_id, purpose): ...


class UnitOfWork(Protocol):
    users: UserRepository
    sessions: SessionRepository
    products: ProductRepository
    orders: OrderRepository
    cart: CartRepository
    wishlist: WishlistRepository
    inventory: InventoryRepository
    tokens: TokenRepository

    def __enter__(self): ...
    def __exit__(self, *args): ...
    def commit(self): ...
    def audit(self, event: str, user_id=None, subject_id=None): ...
    def enqueue(self, kind: str, payload: dict, dedupe_key=None): ...
    def job_exists(self, key: str) -> bool: ...
    def permitted(self, user_id: int, permission: str) -> bool: ...
    def subscribe(self, email: str): ...


class Passwords(Protocol):
    def hash(self, value: str) -> str: ...
    def verify(self, value: str, hashed: str | None) -> bool: ...


class Tokens(Protocol):
    def new(self) -> str: ...
    def digest(self, value: str) -> str: ...


class GoogleIdentity(Protocol):
    def verify(self, credential: str) -> dict: ...
